/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.JOptionPane;
/**
 *
 * @author marco
 */
public class Calculadora extends javax.swing.JInternalFrame {
    // Declaração de variáveis
    private double TEMP;
    private double SolveTEMP;
    Boolean addBool = false;
    Boolean subBool = false;
    Boolean divBool = false;
    Boolean multBool = false;
    Boolean pointBool = false;
    String display = "";
    
    // Método "My Instance"
    private static Calculadora myInstance;
    
        public static Calculadora getInstance(){
            if(myInstance == null) {
                myInstance = new Calculadora();
            }
        
            return myInstance;
        }
        
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelCalculadora = new javax.swing.JPanel();
        botaoSete = new javax.swing.JButton();
        botaoOito = new javax.swing.JButton();
        botaoNove = new javax.swing.JButton();
        botaoQuatro = new javax.swing.JButton();
        botaoCinco = new javax.swing.JButton();
        botaoSeis = new javax.swing.JButton();
        botaoUm = new javax.swing.JButton();
        botaoDois = new javax.swing.JButton();
        botaoTres = new javax.swing.JButton();
        botaoZero = new javax.swing.JButton();
        botaoIgual = new javax.swing.JButton();
        botaoCa = new javax.swing.JButton();
        painelResultado = new javax.swing.JTextField();
        botaoPonto = new javax.swing.JButton();
        botaoSoma = new javax.swing.JButton();
        botaoSubtracao = new javax.swing.JButton();
        botaoDivisao = new javax.swing.JButton();
        botaoMultiplicacao = new javax.swing.JButton();
        botaoCe = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Calculadora");

        botaoSete.setText("7");
        botaoSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSeteActionPerformed(evt);
            }
        });

        botaoOito.setText("8");
        botaoOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOitoActionPerformed(evt);
            }
        });

        botaoNove.setText("9");
        botaoNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNoveActionPerformed(evt);
            }
        });

        botaoQuatro.setText("4");
        botaoQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoQuatroActionPerformed(evt);
            }
        });

        botaoCinco.setText("5");
        botaoCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCincoActionPerformed(evt);
            }
        });

        botaoSeis.setText("6");
        botaoSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSeisActionPerformed(evt);
            }
        });

        botaoUm.setText("1");
        botaoUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUmActionPerformed(evt);
            }
        });

        botaoDois.setText("2");
        botaoDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDoisActionPerformed(evt);
            }
        });

        botaoTres.setText("3");
        botaoTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTresActionPerformed(evt);
            }
        });

        botaoZero.setText("0");
        botaoZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoZeroActionPerformed(evt);
            }
        });

        botaoIgual.setText("=");
        botaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIgualActionPerformed(evt);
            }
        });

        botaoCa.setText("CA");
        botaoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaActionPerformed(evt);
            }
        });

        painelResultado.setBackground(new java.awt.Color(153, 153, 255));
        painelResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painelResultadoActionPerformed(evt);
            }
        });

        botaoPonto.setText(".");
        botaoPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPontoActionPerformed(evt);
            }
        });

        botaoSoma.setBackground(new java.awt.Color(255, 102, 255));
        botaoSoma.setText("+");
        botaoSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSomaActionPerformed(evt);
            }
        });

        botaoSubtracao.setBackground(new java.awt.Color(255, 102, 255));
        botaoSubtracao.setText("-");
        botaoSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSubtracaoActionPerformed(evt);
            }
        });

        botaoDivisao.setBackground(new java.awt.Color(255, 102, 255));
        botaoDivisao.setText("/");
        botaoDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivisaoActionPerformed(evt);
            }
        });

        botaoMultiplicacao.setBackground(new java.awt.Color(255, 102, 255));
        botaoMultiplicacao.setText("*");
        botaoMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMultiplicacaoActionPerformed(evt);
            }
        });

        botaoCe.setText("CE");
        botaoCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCalculadoraLayout = new javax.swing.GroupLayout(painelCalculadora);
        painelCalculadora.setLayout(painelCalculadoraLayout);
        painelCalculadoraLayout.setHorizontalGroup(
            painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculadoraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCalculadoraLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCalculadoraLayout.createSequentialGroup()
                                .addComponent(botaoZero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(painelCalculadoraLayout.createSequentialGroup()
                                    .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botaoQuatro)
                                        .addComponent(botaoSete))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoCinco)
                                        .addComponent(botaoOito))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botaoNove)
                                        .addComponent(botaoSeis)))
                                .addGroup(painelCalculadoraLayout.createSequentialGroup()
                                    .addComponent(botaoUm)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botaoDois)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botaoTres))))
                        .addGap(18, 18, 18)
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCalculadoraLayout.createSequentialGroup()
                                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelCalculadoraLayout.createSequentialGroup()
                                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(botaoSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botaoCa, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(botaoMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoCe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoSubtracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(botaoIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(painelResultado))
                .addGap(19, 19, 19))
        );
        painelCalculadoraLayout.setVerticalGroup(
            painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCalculadoraLayout.createSequentialGroup()
                .addComponent(painelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSete)
                    .addComponent(botaoOito)
                    .addComponent(botaoNove)
                    .addComponent(botaoCa)
                    .addComponent(botaoCe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCalculadoraLayout.createSequentialGroup()
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSoma)
                            .addComponent(botaoSubtracao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoDivisao))
                    .addGroup(painelCalculadoraLayout.createSequentialGroup()
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSeis)
                            .addComponent(botaoCinco)
                            .addComponent(botaoQuatro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoUm)
                            .addComponent(botaoDois)
                            .addComponent(botaoTres)
                            .addComponent(botaoMultiplicacao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCalculadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoPonto)
                            .addComponent(botaoIgual)
                            .addComponent(botaoZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void painelResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painelResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_painelResultadoActionPerformed

    private void botaoSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSeteActionPerformed
        // Botão 7 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "7");
    }//GEN-LAST:event_botaoSeteActionPerformed

    private void botaoOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOitoActionPerformed
        // Botão 8 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "8");
    }//GEN-LAST:event_botaoOitoActionPerformed

    private void botaoNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNoveActionPerformed
        // Botão 9 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "9");
    }//GEN-LAST:event_botaoNoveActionPerformed

    private void botaoQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoQuatroActionPerformed
        // Botão 4 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "4");
    }//GEN-LAST:event_botaoQuatroActionPerformed

    private void botaoCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCincoActionPerformed
        // Botão 5 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "5");
    }//GEN-LAST:event_botaoCincoActionPerformed

    private void botaoSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSeisActionPerformed
        // Botão 6 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "6");
    }//GEN-LAST:event_botaoSeisActionPerformed

    private void botaoUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUmActionPerformed
        // Botão 1 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "1");
    }//GEN-LAST:event_botaoUmActionPerformed

    private void botaoDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDoisActionPerformed
        // Botão 2 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "2");
    }//GEN-LAST:event_botaoDoisActionPerformed

    private void botaoTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTresActionPerformed
        // Botão 3 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "3");
    }//GEN-LAST:event_botaoTresActionPerformed

    private void botaoZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoZeroActionPerformed
        // Botão 0 da calculadora
        display = painelResultado.getText();
        painelResultado.setText(display + "0");
    }//GEN-LAST:event_botaoZeroActionPerformed

    private void botaoPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPontoActionPerformed
        // Botão "ponto" da calculadora
        if(!pointBool) {
            String digitStr = painelResultado.getText();
            if(!digitStr.isEmpty()) {
                display = painelResultado.getText();
                painelResultado.setText(display + ".");
                pointBool = true;
            }
        }
    }//GEN-LAST:event_botaoPontoActionPerformed

    private void botaoSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSomaActionPerformed
        // Botão "soma" da calculadora
        if(!painelResultado.getText().isEmpty()) {
            TEMP = Double.parseDouble(painelResultado.getText());
            painelResultado.setText("");
            addBool = true;
            
            if(pointBool) {
                pointBool = false;
            }
        }
    }//GEN-LAST:event_botaoSomaActionPerformed

    private void botaoSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSubtracaoActionPerformed
        // Botão "subtração" da calculadora
        if(!painelResultado.getText().isEmpty()) {
            TEMP = Double.parseDouble(painelResultado.getText());
            painelResultado.setText("");
            subBool = true;
            
            if(pointBool) {
                pointBool = false;
            }
        }
    }//GEN-LAST:event_botaoSubtracaoActionPerformed

    private void botaoMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMultiplicacaoActionPerformed
        // Botão "multiplicação" da calculadora
        if(!painelResultado.getText().isEmpty()) {
            TEMP = Double.parseDouble(painelResultado.getText());
            painelResultado.setText("");
            multBool = true;
            
            if(pointBool) {
                pointBool = false;
            }
        }
    }//GEN-LAST:event_botaoMultiplicacaoActionPerformed

    private void botaoDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivisaoActionPerformed
        // Botão "divisão" da calculadora
        if(!painelResultado.getText().isEmpty()) {
            TEMP = Double.parseDouble(painelResultado.getText());
            painelResultado.setText("");
            divBool = true;
            
            if(pointBool) {
                pointBool = false;                
            }
        }
    }//GEN-LAST:event_botaoDivisaoActionPerformed

    private void botaoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIgualActionPerformed
        // Botão resultado
        if(!painelResultado.getText().isEmpty()) {
            SolveTEMP = Double.parseDouble(painelResultado.getText());
            if(addBool == true) {
                SolveTEMP = SolveTEMP + TEMP;
            } else if(subBool == true) {
                SolveTEMP = TEMP - SolveTEMP;
            } else if(multBool == true) {
                SolveTEMP = SolveTEMP * TEMP;
            } else if(divBool == true) {
                SolveTEMP = TEMP / SolveTEMP;
            }
            
            painelResultado.setText(Double.toString(SolveTEMP));
            
            addBool = false;
            subBool = false;
            multBool = false;
            divBool = false;
            pointBool = true;
            
        } else {
            JOptionPane.showMessageDialog(this, "O segundo valor é nulo");
            pointBool = true;
            return;
        }
    }//GEN-LAST:event_botaoIgualActionPerformed

    private void botaoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaActionPerformed
        // Botão "clear all" da calculadora
        painelResultado.setText("");
        addBool = false;
        subBool = false;
        multBool = false;
        divBool = false;
        
        TEMP = 0;
        SolveTEMP = 0;
        pointBool = false;
    }//GEN-LAST:event_botaoCaActionPerformed

    private void botaoCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCeActionPerformed
        // Botão "CE" da calculadora
        painelResultado.setText("");
        addBool = false;
        subBool = false;
        multBool = false;
        divBool = false;
        
        TEMP = 0;
        SolveTEMP = 0;
        pointBool = false;
    }//GEN-LAST:event_botaoCeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCa;
    private javax.swing.JButton botaoCe;
    private javax.swing.JButton botaoCinco;
    private javax.swing.JButton botaoDivisao;
    private javax.swing.JButton botaoDois;
    private javax.swing.JButton botaoIgual;
    private javax.swing.JButton botaoMultiplicacao;
    private javax.swing.JButton botaoNove;
    private javax.swing.JButton botaoOito;
    private javax.swing.JButton botaoPonto;
    private javax.swing.JButton botaoQuatro;
    private javax.swing.JButton botaoSeis;
    private javax.swing.JButton botaoSete;
    private javax.swing.JButton botaoSoma;
    private javax.swing.JButton botaoSubtracao;
    private javax.swing.JButton botaoTres;
    private javax.swing.JButton botaoUm;
    private javax.swing.JButton botaoZero;
    private javax.swing.JPanel painelCalculadora;
    private javax.swing.JTextField painelResultado;
    // End of variables declaration//GEN-END:variables
}
