/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import models.ItemCardapio;
import dao.CardapioDAO;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class Cardapio extends javax.swing.JInternalFrame {

    ArrayList<ItemCardapio> ItemCard ;
    MySQL conectar = new MySQL();
    CardapioDAO cardapioDAO = new CardapioDAO();

    private static Cardapio myInstance;

    public static Cardapio getInstance() {
        if (myInstance == null) {
            myInstance = new Cardapio();
        }

        return myInstance;
    }

    public Cardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cardápio");
        setAutoscrolls(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cardápio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 255, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Abrir Cardápio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 680, 130, 50));

        jButton2.setText("Adcionar Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 150, 30));

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 90, -1));

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", "", null}
            },
            new String [] {
                "ID", "Nome", "Ingredientes", "Valor"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 480, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Cardapio.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Nome = JOptionPane.showInputDialog(null, " Nome do Sanduiche: ");
        String Igredientes = JOptionPane.showInputDialog(null, " Principais igredientes: ");
        double Valor = Double.parseDouble(JOptionPane.showInputDialog(null, " valor do sanduiche: "));

       cardapioDAO.inserir(new ItemCardapio(0, Nome, Igredientes, Valor));
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //ItemCard.clear();
        try {
            ItemCard = cardapioDAO.selecionarTodos();
            ArrayList<String> colunas = new ArrayList<String>();
            colunas.add("ID");
            colunas.add("Nome");
            colunas.add("Ingredientes");
            colunas.add("valor");
            jTable1.setModel(utils.TableModelCreator.createTableModel(ItemCardapio.class, ItemCard, colunas));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar Cardapio");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String id = JOptionPane.showInputDialog("ID do item que deseja excluir");
        this.conectar.conectaBanco();
        try {
            this.conectar.updateSQL(
                    "DELETE FROM cardapio "
                    + " WHERE "
                    + "item_ID = '" + id + "'"
                    + ";"
            );
            JOptionPane.showMessageDialog(null, "Item excluido!!");

        } catch (Exception e) {
            System.out.println("Erro ao deletar item " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao deletar item");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String idEdit = JOptionPane.showInputDialog("ID do item que deseja alterar");
        String EditNome = JOptionPane.showInputDialog("Nome:");
        String EditIngredientes = JOptionPane.showInputDialog("Ingredientes:");
        String EditValor = JOptionPane.showInputDialog("Valor:");

        this.conectar.conectaBanco();
        try {
            this.conectar.updateSQL(
                    "UPDATE cardapio "
                    + " SET "
                    + "item_nome = '" + EditNome + "',"
                    + "Item_Igredientes = '" + EditIngredientes + "',"
                    + "item_Valor = '" + EditValor + "'"
                    + " WHERE "
                    + "item_ID = '" + idEdit + "'"
                    + ";"
            );
            JOptionPane.showMessageDialog(null, "Item Editado!");

        } catch (Exception e) {
            System.out.println("Erro ao deletar item " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao deletar item");
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
